vich_uploader:
    db_driver: orm

    metadata :
        type : attribute

    mappings:
        images:
            uri_prefix: /images/imageavatar
            upload_destination: '%kernel.project_dir%/public/images/imagearticle'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
